export interface Internacion {
    INNumInt:           number
    INNumero?:          number
    INHabitacion?:      number
    INCama?:            number
    INAcomp?:           string
    INAislado?:         string
    INMedicoEnvia?:     number
    INMedicoInterna?:   number
    INServIngreso?:     number
    INFechaIngreso?:    Date
    INHoraIngreso?:     string
    INDiagIngreso?:     string
    INMotivoIngreso?:   string
    INOrdenInternacion?:string
    INFechaEgreso?:     Date
    INHoraEgreso?:      string
    INDiagEgreso?:      string
    INMotivoEgreso?:    string
    INServActual?:      number
    INDiagActual?:      string
    INObraSocial?:      number
    INPlan?:            string
    INNumAfiliado?:     string
    INTipoIva?:         number
    INCuit?:            string
    INFechaFacturado?:  Date
    INHoraFacturado?:   string
    INUsuario?:         string
    INFechaSis?:        Date
    INHoraSis?:         string
    INFechaCerrado?:    Date
    INICD10Ingreso?:    string
    INICD10Actual?:     string
    INICD10Egreso?:     string
    INICD10Eg2?:        string
    INICD10Eg3?:        string
    InDerivaCabe?:      string
    INHCNumIng?:        number
    INMedCabecera?:     number
    INIndComp?:         string
    INProgramada?:      string
    INOSPLan?:          string
    INAfilOblig?:       string
    INFinCobertura?:    number
    INImpCaucion?:      number
    INCargoPaciente?:   string
    INEstFecAlta?:      Date
    INEstImporte?:      number
    INImpPagado?:       number
    INProced?:          string
    INProcSubCo?:       string
    INReNombre?:        string
    INReParentesco?:    string
    INReDomicilio?:     string
    INReCodArea?:       string
    INReTelefono?:      string
    InRe2CodArea?:      string
    InRe2Telefono?:     string
    InReUrgCodArea?:    string
    INReTelUrg?:        string
    InReCelular?:       string
    InReCorreo?:        string
    INReLocalidad?:     number
    INReProvincia?:     number
    INReCodPost?:       string
    INReTipoDoc?:       number
    INReNumDocum?:      number
    InOperado?:         string
    InFechaOperado?:    Date
    InAtc?:             string
    InFechaAtc?:        Date
    InIntrnaAnt?:       string
    InFechaIntAnt?:     Date
    InLugInterna?:      string
    InUlDiaInter?:      string
    INInterPolicial?:   string
    INInterJudicial?:   string
    INOrigen?:          number
    INDestEgreso?:      number
    INEgFechaSis?:      Date
    INEgHoraSis?:       string
    INICD10Eg4?:        string
    INFeModif?:         Date
    INUsModif?:         string
    INModulado?:        string
    INMedSegui?:        number
    INMedEpicrisis?:    number
    INProtocolo?:       number
    INFecProtocolo?:    Date
    INFinFecProtocolo?: Date
    INAutOSDE?:         number
    INTrnOSDE?:         number
    INNoCheq?:          string
    INAproOSDE?:        string
    INNumOrdOSDE?:      number
    INTrnEgrOSDE?:      number
    INEstCardio?:       string
    INSinModLab?:       string
    INTC?:              string
    INLugar?:           number
    INEvId?:            number
    INObsAudit?:        string
    INMeCardioCab?:     number
    INHCOrig?:          number
    INDocFirma?:        string
    INUOActual?:        number
    INEgreIAM?:         string
    INEgreIC?:          string
    INEgreIAM2?:        string
    INEgreIC2?:         string
    INEgreIAM3?:        string
    INEgreIC3?:         string
    INEgreIAM4?:        string
    INEgreIC4?:         string
    INFecPreAlta?:      Date
    INPreObs?:          string
    INPreAltaMed?:      number
    INPreALtaFec?:      Date
    INFecAltaMed?:      Date
    INUsuAltaMed?:      string
    INTipoRelMSeg?:     string
    INConRemoto?:       string
    INConsen?:          string
    INDelEmisOSDE?:     string
    INUsuEgre?:         string
    INFecEgre?:         Date
    INTermAlta?:        string
    INTermEgre?:        string
    INProg?:            string
    INTpoAisla?:        string
    INHorPreAlta?:      string
    INFecHorPreAlta?:   Date
    INFecFinCob?:       Date
    INBiblioteca?:      number
    INCapita?:          string
    INImpPulsera?:      string
    INFecImpPulsera?:   Date
    INEstHoraAlta?:     string
    INEstFecHoraAlta?:  Date
    INEstFecIngreAlta?: Date
    INEstUsuAlta?:      string
    INIBCodigo?:        string
    INIBFecha?:         Date
    INRef2Nom?:         string
    INRef2Tel?:         string
    INRef2Obs?:         string
    INRef3Nom?:         string
    INRef3Tel?:         string
    INRef3Obs?:         string
    INRef1Obs?:         string
    INFlgHCEId?:        number
    INPINumIng?:        number
    INEncuestaId?:      number
    INEncuestaTS?:      Date
    ININNumOrign?:      number
    INTipoOrdOSDE?:     number
    INFlgHCEUsu?:       string
    INFlgHCEFec?:       Date
    INClasifPM?:        string
    INAislaIdInd?:      number
    INAislaCuando?:     Date
    INAislaIdIndBaja?:  number
    INAislaUsuBaja?:    string
    INAislaCuandoBaja?: Date
    INTpoInt?:          string
    INToken?:           string
    INExisVerifUsu?:    string
    INExitVerifFec?:    Date
    INExitVerif?:       string
    INEgreVerifUsu?:    string
    INEgreVerifFec?:    Date
    INEgreVerif?:       string
    INARMHasta?:        Date
    INARMDesde?:        Date
    INARM?:             string
    INObsAuditFecha?:   Date
    INObsAuditUsu?:     string
    INRNQueOrden?:      number
    INRNNumInt?:        number
    INRN?:              string
}
