interface Especialidad {
    ESCodigo: number;
    ESDescripcion?: string;
    ESUsuario?: string;
    ESFechaAlta?: Date;
    EsTecnologia?: number;
    EsRenglones?: number;
    EsMedicos?: string;
    ESTerminal?: string;
    ESfecModif?: Date;
    ESUsuModif?: string;
    ESGrpAlert?: string;
    ESPedConsHCE?: string;
    ESPIndicaciones?: string;
    ESDscAmp?: string;
    ESNNCodigo?: number;
    EsHabilitadoWeb?: string;
}

export interface Medico {
    MECodigo:               number
    METratamiento?:         string
    MEApellido?:            string
    MENom?:                 string
    MENombre?:              string
    MEIntExt?:              string
    MEEspecialidad?:        number
    MEDireccion?:           string
    MECodArea?:             string
    METelefono?:            string
    MECelular?:             string
    MECodPostal?:           string
    MELocalidad?:           number
    MEProvincia?:           number
    MEPais?:                number
    MECDireccion?:          string
    MECCodArea?:            string
    MECTelefono?:           string
    MECCodPostal?:          string
    MECLocalidad?:          number
    MECProvincia?:          number
    MECPais?:               number
    MECHorario?:            string
    MECSecretaria?:         string
    MEZona?:                string
    MELugCorresp?:          string
    MEEmail?:               string
    MECondIva?:             number
    MECuit?:                string
    MEConcFijos?:           string
    MeViCodigo?:            number
    MEPacDerivados?:        number
    MEFechaUltimoPaciente?: Date
    MEFechaIng?:            Date
    MEFechaAlta?:           Date
    MEUsuario?:             string
    MEFechaSis?:            Date
    MEHoraSis?:             string
    MeOMCodigo?:            string
    MEMatricula?:           number
    MEMatProvin?:           number
    MELoteTransferencia?:   number
    MERenumerar?:           number
    MEFechaBaja?:           Date
    MEUsBaja?:              string
    MECategoria?:           string
    MEOriginal?:            number
    MeOrigen?:              string
    MeTipoDoc?:             number
    MeNumDoc?:              number
    MeEstCivil?:            string
    MeFechaNac?:            Date
    MeCargoHospit?:         string
    MEMarcaMailing?:        string
    MeInicApeNom?:          string
    MeProcEpicrisis?:       string
    MeEsCirujano?:          string
    MeEsAnes?:              string
    MeEsInstru?:            string
    MeEsPerfu?:             string
    MeRelacion?:            string
    MeWebUsu?:              string
    MeWebPws?:              string
    MeWebUltAcc?:           Date
    MeWebHab?:              string
    MeInvestiga?:           string
    MeFecModif?:            Date
    MeUsModif?:             string
    MeNoVisitar?:           string
    MeLlamarTE?:            string
    MeNoCab?:               string
    MESexo?:                string
    MEHcNumIng?:            number
    MEMotBaja?:             number
    MeCtaTpo?:              number
    MeCtaNro?:              number
    MeCtaBcoCod?:           number
    MeCtaCBU?:              string
    MeHobbies?:             string
    MeHCOrig?:              number
    MEPacDerCabecera?:      number
    MEFeUltPacCabecera?:    Date
    MeEsHemo?:              string
    MeFoto?:                Buffer
    MeFacHon?:              string
    MeBiblioteca?:          number
    MeMatVto?:              Date
    MeSegMP?:               string
    MeSegMPCia?:            string
    MeSegMPNPol?:           string
    MeSegMPVto?:            Date
    MeSegMPImp?:            number
    MeEntEmp?:              number
    MeEntId?:               number
    MeObsTur?:              string
    MeObsCons?:             string
    MePerFisJur?:           string
    MeEsAgruMed?:           string
    MeEnAgruMed?:           number
    MeIntegrado?:           string
    MeEsEnfermero?:         string
    MeIIBBCod?:             number
    MeIIBBNum?:             number
    MeIIBBNoCaba?:          string
    MeToken?:               string
    MeZoomID?:              string
    MEERPCtaVta?:           string
    MEERPCtaCob?:           string
    MEEmpLegajo?:           number
    MEEsEmp?:               string
    especialidad:           Especialidad | null
}
