interface Contrato {
    OSCodigo:         number
    CoPlan:           string
    CoNomPlan?:       string
    ArCodigo?:        string
    CoVigenDesde?:    Date
    CoVigenHasta?:    Date
    CoRespNormas?:    string
    CoUsAlta?:        string
    CoFechaAlta?:     Date
    CoUsModif?:       string
    CoFechaModif?:    Date
    CoNormAnes?:      string
    CoNormAneCod?:    number
    CoSiPres?:        string
    CoValorCapita?:   number
    CoPorDesc?:       number
    CoDesDesc?:       string
    CoRedondeo?:      string
    CoUltVigPre?:     Date
    CoIncUrgGuar?:    number
    CoBiblioteca?:    number
    CoBlqEdtCob?:     string
    CoExterno?:       string
    CoFacGru?:        string
    CoModMasEventos?: string
    CoCapitado?:      string
    CoNNmasNBU?:      string
}

export interface ObraSocial {
    OSCodigo:             number
    OSTipoCliente?:       number
    OSRazonSocial?:       string
    OSPriv?:              string
    OSCalle?:             string
    OSNumCale?:           number
    OSPiso?:              string
    OSDepto?:             string
    OSTelefono?:          string
    OSFax?:               string
    OSLocalidad?:         number
    OSCodPostal?:         string
    OSProvincia?:         number
    OSPais?:              number
    OSCCalle?:            string
    OSCNumCalle?:         number
    OSCPiso?:             string
    OSCDepto?:            string
    OSCTelefono?:         string
    OSCFax?:              string
    OSCLocalidad?:        number
    OSCCodPostal?:        string
    OSCProvincia?:        number
    OSCPais?:             number
    OSTipoIva?:           number
    OSIvaDiferencial?:    number
    OSCuit?:              number
    OSDiaCierre?:         number
    OSDiasVencimiento?:   number
    OSVigente?:           string
    OSUsuario?:           string
    OSFechaSis?:          Date
    OSHoraSis?:           string
    OSCondVen?:           number
    OSConcFijo?:          number
    OSConcPorcentaje?:    number
    OSIncCargPacientes?:  string
    OSCodGrupo?:          number
    OSCapita?:            string
    OSValMaeCap?:         string
    OSValorCapita?:       number
    OSImpPieFac?:         string
    OSObliAdhe?:          string
    OSFacAmResumida?:     string
    OSFacInResumida?:     string
    OSCategoria?:         string
    OSUsModif?:           string
    OSFechaModif?:        Date
    OSEMail?:             string
    OSDesdePosBanda?:     number
    OSLargoBanda?:        number
    OSDesdPosApe?:        number
    OSLargoPosApe?:       number
    OSModRefactura?:      string
    OSGenerico?:          string
    OSEmpresa?:           number
    OSMultiEmp?:          string
    OSResumido?:          string
    OSManejoTurnos?:      string
    OSCanTurnosMes?:      number
    OSPresNro?:           string
    OSPresNom?:           string
    OSPresMed?:           string
    OSPresPrac?:          string
    OSOSACod?:            number
    OSPideCapita?:        string
    OSSinPapeles?:        string
    OSSigla?:             string
    OSDigitaliza?:        string
    OSGrpAlerSinPapeles?: string
    OSFacElec?:           string
    OSDigDoc?:            string
    OSImpPerFac?:         string
    OSSendCmpMail?:       string
    OSFacCopias?:         number
    OSBiblioteca?:        number
    OSMailEnvio?:         string
    OSMailTexto?:         string
    OSNoTurWeb?:          string
    OSObsTurWeb?:         string
    OSMsgMedAmbu?:        string
    OSMsgMedInter?:       string
    OSIIBBNum?:           number
    OSIIBBCod?:           number
    OSIIBBNoCABA?:        string
    OSEntEmp?:            number
    OSEntId?:             number
    OSFCalle?:            string
    OSFNumCalle?:         number
    OSFPiso?:             string
    OSFDepto?:            string
    OSFLocalidad?:        number
    OSFCodPostal?:        string
    OSFProvincia?:        number
    OSFPais?:             number
    OSCodActivia?:        string
    OSAux1?:              string
    OSAux2?:              string
    OSAux3?:              string
    OSAux4?:              string
    OSAux5?:              string
    OSRefComercial?:      string
    OSRefFinanciero?:     string
    OSEnviaCenso?:        string
    OSMailEnvioCenso?:    string
    OSUltimoCenso?:       Date
    OSPerFisJur?:         string
    OSFechaSusp?:         Date
    OSPreFijo?:           string
    OSConcImporte?:       number
    OSERPCtaVta?:         string
    OSERPCtaCob?:         string
    OSPresMedCnt?:        number
    OSEnviaInfMed?:       string
    OSMailEnvioInfMed?:   string
    OSUltimoInfMed?:      Date
    OSEnviaFacturas?:     string
    OSMailEnvioFac?:      string
    OSUltimoFac?:         Date
    OSPideAfilSer?:       string
    OSGranContruyente?:   string
    OSHabilitadoWeb?:     string
    OSMedicos?:           string
    OSFmtPrescrip?:       number
    OSFmtReceta?:         number
    OSDscWEB?:            string
    plan:                 Contrato | null
}